const songLibrary = [
  {t: "(Dont Fear) The Reaper", a: "Blue Öyster Cult", y: 1976},
{t: "(I Cant Get No) Satisfaction", a: "The Rolling Stones", y: 1965},
{t: "(Sittin On) the Dock of the Bay", a: "Otis Redding", y: 1967},
{t: "(White Man) in Hammersmith Palais", a: "The Clash", y: 1978},
{t: "(You Make Me Feel Like) A Natural Woman", a: "Aretha Franklin", y: 1967},
{t: "...Baby One More Time", a: "Britney Spears", y: 1998},
{t: "1999", a: "Prince", y: 1982},
{t: "212", a: "Azealia Banks", y: 2011},
{t: "99 Problems", a: "Jay-Z", y: 2003},
{t: "A Case of You", a: "Joni Mitchell", y: 1971},
{t: "A Change Is Gonna Come", a: "Sam Cooke", y: 1964},
{t: "A Day in the Life", a: "The Beatles", y: 1967},
{t: "A Milli", a: "Lil Wayne", y: 2009},
{t: "A Whiter Shade of Pale", a: "Procol Harum", y: 1967},
{t: "A&W", a: "Lana Del Rey", y: 2023},
{t: "Ace of Spades", a: "Motörhead", y: 1980},
{t: "Adore", a: "Prince", y: 1987},
{t: "Africa", a: "Toto", y: 1982},
{t: "After the Gold Rush", a: "Neil Young", y: 1970},
{t: "Aint No Sunshine", a: "Bill Withers", y: 1971},
{t: "Aint Nobody", a: "Rufus and Chaka Khan", y: 1983},
{t: "Alison", a: "Elvis Costello", y: 1977},
{t: "Alive", a: "Pearl Jam", y: 1991},
{t: "All Along the Watchtower", a: "The Jimi Hendrix Experience", y: 1968},
{t: "All I Have to Do Is Dream", a: "Everly Brothers", y: 1958},
{t: "All My Friends", a: "LCD Soundsystem", y: 2007},
{t: "All Too Well", a: "Taylor Swift", y: 2012},
{t: "All the Young Dudes", a: "Mott the Hoople", y: 1972},
{t: "Alright", a: "Kendrick Lamar", y: 2015},
{t: "American Girl", a: "Tom Petty and the Heartbreakers", y: 1976},
{t: "American Tune", a: "Paul Simon", y: 1973},
{t: "Amor Prohibido", a: "Selena", y: 1994},
{t: "Anarchy in the U.K.", a: "Sex Pistols", y: 1977},
{t: "Angel From Montgomery", a: "John Prine", y: 1971},
{t: "Anti-Hero", a: "Taylor Swift", y: 2022},
{t: "Are You That Somebody?", a: "Aaliyah", y: 1998},
{t: "As It Was", a: "Harry Styles", y: 2022},
{t: "At Last", a: "Etta James", y: 1960},
{t: "Atlantic City", a: "Bruce Springsteen", y: 1982},
{t: "B.O.B.", a: "Outkast", y: 2000},
{t: "Baba ORiley", a: "The Who", y: 1971},
{t: "Back That Azz Up", a: "Juvenile feat. Lil Wayne and Mannie Fresh", y: 1998},
{t: "Back to Black", a: "Amy Winehouse", y: 2006},
{t: "Bad Guy", a: "Billie Eilish", y: 2019},
{t: "Bad Reputation", a: "Joan Jett", y: 1980},
{t: "Bad Romance", a: "Lady Gaga", y: 2009},
{t: "Bad and Boujee", a: "Migos feat. Lil Uzi Vert", y: 2016},
{t: "Bam Bam", a: "Sister Nancy", y: 1982},
{t: "Basket Case", a: "Green Day", y: 1994},
{t: "Be My Baby", a: "The Ronettes", y: 1963},
{t: "Be Thankful for What You Got", a: "William DeVaughn", y: 1974},
{t: "Beat It", a: "Michael Jackson", y: 1982},
{t: "Because the Night", a: "Patti Smith", y: 1978},
{t: "Believe", a: "Cher", y: 1998},
{t: "Bennie and the Jets", a: "Elton John", y: 1973},
{t: "Big Poppa", a: "The Notorious B.I.G.", y: 1994},
{t: "Billie Jean", a: "Michael Jackson", y: 1982},
{t: "Billie Jean", a: "Michael Jackson", y: 1982},
{t: "Birds of a Feather", a: "Billie Eilish", y: 2024},
{t: "Bizarre Love Triangle", a: "New Order", y: 1986},
{t: "Black Hole Sun", a: "Soundgarden", y: 1994},
{t: "Blank Space", a: "Taylor Swift", y: 2014},
{t: "Blinding Lights", a: "The Weeknd", y: 2019},
{t: "Blitzkrieg-Bop", a: "Ramones", y: 1976},
{t: "Blowin in the Wind", a: "Bob Dylan", y: 1963},
{t: "Blue Eyes Crying in the Rain", a: "Willie Nelson", y: 1975},
{t: "Blue Monday", a: "New Order", y: 1983},
{t: "Blueberry Hill", a: "Fats Domino", y: 1956},
{t: "Bo Diddley", a: "Bo Diddley", y: 1955},
{t: "Bohemian Rhapsody", a: "Queen", y: 1975},
{t: "Bohemian Rhapsody", a: "Queen", y: 1975},
{t: "Boom Boom", a: "John Lee Hooker", y: 1962},
{t: "Born to Run", a: "Bruce Springsteen", y: 1975},
{t: "Both Sides Now", a: "Joni Mitchell", y: 1969},
{t: "Box of Rain", a: "The Grateful Dead", y: 1970},
{t: "Boys of Summer", a: "Don Henley", y: 1984},
{t: "Brass in Pocket", a: "Pretenders", y: 1979},
{t: "Break My Soul", a: "Beyonce", y: 2022},
{t: "Bridge Over Troubled Water", a: "Simon and Garfunkel", y: 1970},
{t: "Bring the Noise", a: "Public Enemy", y: 1987},
{t: "Buddy Holly", a: "Weezer", y: 1994},
{t: "Buffalo Stance", a: "Neneh Cherry", y: 1988},
{t: "C.R.E.A.M.", a: "Wu-Tang Clan", y: 1994},
{t: "California Dreamin", a: "The Mamas and the Papas", y: 1965},
{t: "California Love", a: "2Pac", y: 1995},
{t: "Call Me Maybe", a: "Carly Rae Jepsen", y: 2012},
{t: "Can I Kick It?", a: "A Tribe Called Quest", y: 1990},
{t: "Cannonball", a: "The Breeders", y: 1993},
{t: "Chain of Fools", a: "Aretha Franklin", y: 1967},
{t: "Changes", a: "David Bowie", y: 1971},
{t: "Cissy Strut", a: "The Meters", y: 1969},
{t: "Closer", a: "Nine Inch Nails", y: 1994},
{t: "Coal Miners Daughter", a: "Loretta Lynn", y: 1970},
{t: "Coat of Many Colors", a: "Dolly Parton", y: 1971},
{t: "Come as You Are", a: "Nirvana", y: 1991},
{t: "Comfortably Numb", a: "Pink Floyd", y: 1979},
{t: "Common People", a: "Pulp", y: 1996},
{t: "Cosmic Dancer", a: "T. Rex", y: 1971},
{t: "Could You Be Loved", a: "Bob Marley and the Wailers", y: 1980},
{t: "Cranes in the Sky", a: "Solange", y: 2016},
{t: "Crazy", a: "Patsy Cline", y: 1961},
{t: "Crazy", a: "Gnarls Barkley", y: 2006},
{t: "Crazy In Love", a: "Beyoncé", y: 2003},
{t: "Crazy in Love", a: "Beyoncé feat. Jay-Z", y: 2003},
{t: "Creep", a: "Radiohead", y: 1992},
{t: "Creep", a: "Radiohead", y: 1992},
{t: "Criminal", a: "Fiona Apple", y: 1996},
{t: "Cross Road Blues", a: "Robert Johnson", y: 1937},
{t: "Cruel Summer", a: "Taylor Swift", y: 2019},
{t: "Crying", a: "Roy Orbison", y: 1962},
{t: "Da Doo Ron Ron", a: "The Crystals", y: 1963},
{t: "Dancing Queen", a: "ABBA", y: 1976},
{t: "Dancing Queen", a: "ABBA", y: 1976},
{t: "Dancing in the Street", a: "Martha and the Vandellas", y: 1964},
{t: "Dancing on My Own", a: "Robyn", y: 2010},
{t: "Deacon Blues", a: "Steely Dan", y: 1977},
{t: "Desolation Row", a: "Bob Dylan", y: 1965},
{t: "Divorce Song", a: "Liz Phair", y: 1993},
{t: "Doll Parts", a: "Hole", y: 1994},
{t: "Dont Leave Me This Way", a: "Thelma Houston", y: 1976},
{t: "Dont Stop Believin", a: "Journey", y: 1981},
{t: "Doo Wop (That Thing)", a: "Lauryn Hill", y: 1998},
{t: "Dream On", a: "Aerosmith", y: 1973},
{t: "Dreams", a: "Fleetwood Mac", y: 1977},
{t: "Dreams", a: "Fleetwood Mac", y: 1977},
{t: "Drivers License", a: "Olivia Rodrigo", y: 2021},
{t: "Drivers License", a: "Olivia Rodrigo", y: 2021},
{t: "Dynamite", a: "BTS", y: 2020},
{t: "Edge of Seventeen", a: "Stevie Nicks", y: 1981},
{t: "Eight Miles High", a: "The Byrds", y: 1966},
{t: "Eleanor Rigby", a: "The Beatles", y: 1966},
{t: "Ella Baila Sola", a: "Eslabon Armado and Peso Pluma", y: 2023},
{t: "Enjoy the Silence", a: "Depeche Mode", y: 1990},
{t: "Enter Sandman", a: "Metallica", y: 1991},
{t: "Essence", a: "Wizkid feat. Tems", y: 2021},
{t: "Ever Fallen in Love (With Someone You Shouldntve)", a: "Buzzcocks", y: 1978},
{t: "Everlong", a: "Foo Fighters", y: 1997},
{t: "Every Breath You Take", a: "The Police", y: 1983},
{t: "Everybody Wants to Rule the World", a: "Tears for Fears", y: 1985},
{t: "Everyday People", a: "Sly and the Family Stone", y: 1968},
{t: "Fade Into You", a: "Mazzy Star", y: 1993},
{t: "Family Affair", a: "Sly and the Family Stone", y: 1971},
{t: "Fantasy", a: "Mariah Carey", y: 1995},
{t: "Fast Car", a: "Tracy Chapman", y: 1988},
{t: "Father and Son", a: "Cat Stevens/Yusuf", y: 1970},
{t: "Fight the Power", a: "Public Enemy", y: 1989},
{t: "Fire and Rain", a: "James Taylor", y: 1970},
{t: "Fix You", a: "Coldplay", y: 2005},
{t: "Flash Light", a: "Parliament", y: 1977},
{t: "Formation", a: "Beyoncé", y: 2016},
{t: "Fortunate Son", a: "Creedence Clearwater Revival", y: 1969},
{t: "Free Bird", a: "Lynyrd Skynyrd", y: 1973},
{t: "Free Fallin”", a: "Tom Petty", y: 1989},
{t: "Freedom! 90", a: "George Michael", y: 1990},
{t: "Fuck tha Police", a: "N.W.A", y: 1988},
{t: "Gangsta's Paradise", a: "Coolio", y: 1995},
{t: "Gasolina", a: "Daddy Yankee", y: 2010},
{t: "Georgia on My Mind", a: "Ray Charles", y: 1960},
{t: "Get Lucky", a: "Daft Punk", y: 2013},
{t: "Get Lucky", a: "Daft Punk feat. Pharrell Williams", y: 2013},
{t: "Get Up", a: "The Wailers", y: 1973},
{t: "Get Up (I Feel Like Being A) Sex Machine", a: "James Brown", y: 1970},
{t: "Get Ur Freak On", a: "Missy Elliott", y: 2001},
{t: "Gimme Shelter", a: "The Rolling Stones", y: 1969},
{t: "Gloria", a: "Patti Smith", y: 1975},
{t: "Gloria", a: "Them", y: 1965},
{t: "Go Your Own Way", a: "Fleetwood Mac", y: 1977},
{t: "God Only Knows", a: "The Beach Boys", y: 1966},
{t: "God Save the Queen", a: "Sex Pistols", y: 1977},
{t: "Good Golly", a: "Little Richard", y: 1958},
{t: "Good Times", a: "Chic", y: 1979},
{t: "Good Vibrations", a: "The Beach Boys", y: 1966},
{t: "Goodbye Earl", a: "Dixie Chicks", y: 2000},
{t: "Grace", a: "Jeff Buckley", y: 1994},
{t: "Great Balls of Fire", a: "Jerry Lee Lewis", y: 1957},
{t: "Green Onions", a: "Booker T. and the MGs", y: 1962},
{t: "Grindin”", a: "Clipse", y: 2002},
{t: "Groove Is in the Heart", a: "Deee-Lite", y: 1990},
{t: "Hallelujah", a: "Leonard Cohen", y: 1984},
{t: "Happy", a: "Pharrell Williams", y: 2013},
{t: "He Stopped Loving Her Today", a: "George Jones", y: 1980},
{t: "Heart of Glass", a: "Blondie", y: 1979},
{t: "Heart of Gold", a: "Neil Young", y: 1972},
{t: "Heartbreak Hotel", a: "Elvis Presley", y: 1958},
{t: "Heat Wave", a: "Martha Reeves and the Vandellas", y: 1963},
{t: "Heavy Metal Drummer", a: "Wilco", y: 2002},
{t: "Help Me", a: "Joni Mitchell", y: 1974},
{t: "Help!", a: "The Beatles", y: 1965},
{t: "Heroes", a: "David Bowie", y: 1977},
{t: "Hey Jude", a: "The Beatles", y: 1968},
{t: "Hey Ya!", a: "Outkast", y: 2003},
{t: "Hey Ya!", a: "Outkast", y: 2003},
{t: "Higher Ground", a: "Stevie Wonder", y: 1973},
{t: "Hold On", a: "Drake feat. Majid Jordan", y: 2013},
{t: "Hotel California", a: "Eagles", y: 1976},
{t: "Hotel California", a: "The Eagles", y: 1976},
{t: "Hotline Bling", a: "Drake", y: 2015},
{t: "Hound Dog", a: "Big Mama Thornton", y: 1953},
{t: "House of Balloons", a: "The Weeknd", y: 2011},
{t: "How Soon Is Now?", a: "The Smiths", y: 1984},
{t: "Hungry Like the Wolf", a: "Duran Duran", y: 1982},
{t: "I Cant Help Myself (Sugar Pie", a: "The Four Tops", y: 1965},
{t: "I Cant Make You Love Me", a: "Bonnie Raitt", y: 1991},
{t: "I Cant Stand the Rain", a: "Ann Peebles", y: 1973},
{t: "I Feel Love", a: "Donna Summer", y: 1977},
{t: "I Heard It Through the Grapevine", a: "Marvin Gaye", y: 1968},
{t: "I Only Have Eyes for You", a: "The Flamingos", y: 1959},
{t: "I Put a Spell on You", a: "Screamin’ Jay Hawkins", y: 1956},
{t: "I Say a Little Prayer", a: "Aretha Franklin", y: 1968},
{t: "I Still Havent Found What Im Looking For", a: "U2", y: 1987},
{t: "I Walk the Line", a: "Johnny Cash", y: 1956},
{t: "I Wanna Be Your Dog", a: "The Stooges", y: 1969},
{t: "I Wanna Dance With Somebody (Who Loves Me)", a: "Whitney Houston", y: 1987},
{t: "I Wanna Dance with Somebody", a: "Whitney Houston", y: 1987},
{t: "I Want It That Way", a: "Backstreet Boys", y: 1999},
{t: "I Want You Back", a: "The Jackson 5", y: 1969},
{t: "I Want to Hold Your Hand", a: "The Beatles", y: 1963},
{t: "I Want to Hold Your Hand", a: "The Beatles", y: 1963},
{t: "I Will Always Love You", a: "Whitney Houston", y: 1992},
{t: "I Will Survive", a: "Gloria Gaynor", y: 1978},
{t: "Idioteque", a: "Radiohead", y: 2000},
{t: "If I Aint Got You", a: "Alicia Keys", y: 2003},
{t: "Ill Take You There", a: "The Staple Singers", y: 1972},
{t: "Im Coming Out", a: "Diana Ross", y: 1980},
{t: "Im So Lonesome I Could Cry", a: "Hank Williams", y: 1949},
{t: "Im Waiting for the Man", a: "The Velvet Underground", y: 1967},
{t: "Im a Believer", a: "The Monkees", y: 1966},
{t: "Imagine", a: "John Lennon", y: 1971},
{t: "In Da Club", a: "50 Cent", y: 2003},
{t: "In My Life", a: "The Beatles", y: 1965},
{t: "In the Air Tonight", a: "Phil Collins", y: 1981},
{t: "In the Midnight Hour", a: "Wilson Pickett", y: 1965},
{t: "In the Still of the Night", a: "The Five Satins", y: 1956},
{t: "Intl Players Anthem (I Choose You)", a: "UGK feat. Outkast", y: 2007},
{t: "Into the Groove", a: "Madonna", y: 1985},
{t: "Into the Mystic", a: "Van Morrison", y: 1970},
{t: "Iron Man", a: "Black Sabbath", y: 1971},
{t: "It Takes Two", a: "Rob Base and DJ E-Z Rock", y: 1988},
{t: "It Was a Good Day", a: "Ice Cube", y: 1992},
{t: "Its Too Late", a: "Carole King", y: 1971},
{t: "J Balvin", a: "Cardi B", y: 2018},
{t: "Jailhouse Rock", a: "Elvis Presley", y: 1957},
{t: "Johnny B. Goode", a: "Chuck Berry", y: 1958},
{t: "Jolene", a: "Dolly Parton", y: 1974},
{t: "Juicy", a: "Notorious B.I.G.", y: 1994},
{t: "Jump", a: "Van Halen", y: 1983},
{t: "Jumpin Jack Flash", a: "The Rolling Stones", y: 1968},
{t: "Jungleland", a: "Bruce Springsteen", y: 1975},
{t: "Just Like Heaven", a: "The Cure", y: 1987},
{t: "Just What I Needed", a: "The Cars", y: 1978},
{t: "Just a Friend", a: "Biz Markie", y: 1989},
{t: "Karma Police", a: "Radiohead", y: 1997},
{t: "Kashmir", a: "Led Zeppelin", y: 1975},
{t: "Kill Bill", a: "SZA", y: 2022},
{t: "Killing Me Softly With His Song", a: "Roberta Flack", y: 1973},
{t: "Killing Me Softly With His Song", a: "Fugees", y: 1996},
{t: "Killing in the Name", a: "Rage Against the Machine", y: 1992},
{t: "King Tubby Meets the Rockers Uptown", a: "Augustus Pablo", y: 1974},
{t: "Kiss", a: "Prince", y: 1986},
{t: "Ku Klux Klan", a: "Steel Pulse", y: 1978},
{t: "LL Cool J", a: "Craig Mack feat. Notorious B.I.G.", y: 1994},
{t: "La Vida Es un Carnaval", a: "Celia Cruz", y: 1998},
{t: "Landslide", a: "Fleetwood Mac", y: 1975},
{t: "Last Nite", a: "The Strokes", y: 2001},
{t: "Layla", a: "Derek and the Dominos", y: 1970},
{t: "Leader of the Pack", a: "The Shangri-Las", y: 1964},
{t: "Lean on Me", a: "Bill Withers", y: 1972},
{t: "Left of the Dial", a: "The Replacements", y: 1985},
{t: "Let It Be", a: "The Beatles", y: 1970},
{t: "Lets Get It On", a: "Marvin Gaye", y: 1973},
{t: "Lets Stay Together", a: "Al Green", y: 1971},
{t: "Levitating", a: "Dua Lipa", y: 2020},
{t: "Life on Mars?", a: "David Bowie", y: 1971},
{t: "Light My Fire", a: "The Doors", y: 1967},
{t: "Like a Prayer", a: "Madonna", y: 1989},
{t: "Like a Rolling Stone", a: "Bob Dylan", y: 1965},
{t: "Like a Virgin", a: "Madonna", y: 1984},
{t: "Limelight", a: "Rush", y: 1981},
{t: "Little Red Corvette", a: "Prince", y: 1982},
{t: "Little Wing", a: "The Jimi Hendrix Experience", y: 1967},
{t: "Livin on a Prayer", a: "Bon Jovi", y: 1986},
{t: "Livin' on a Prayer", a: "Bon Jovi", y: 1986},
{t: "Lola", a: "The Kinks", y: 1970},
{t: "London Calling", a: "The Clash", y: 1980},
{t: "Lose Yourself", a: "Eminem", y: 2002},
{t: "Lose Yourself", a: "Eminem", y: 2002},
{t: "Loser", a: "Beck", y: 1993},
{t: "Losing My Religion", a: "R.E.M.", y: 1991},
{t: "Louie Louie", a: "The Kingsmen", y: 1963},
{t: "Love Will Tear Us Apart", a: "Joy Division", y: 1980},
{t: "Love and Happiness", a: "Al Green", y: 1972},
{t: "Lust for Life", a: "Iggy Pop", y: 1977},
{t: "Maggie May", a: "Rod Stewart", y: 1971},
{t: "Mama Tried", a: "Merle Haggard", y: 1968},
{t: "Mannish Boy", a: "Muddy Waters", y: 1955},
{t: "Maps", a: "Yeah Yeah Yeahs", y: 2003},
{t: "Marquee Moon", a: "Television", y: 1977},
{t: "Master of Puppets", a: "Metallica", y: 1986},
{t: "Maybelline", a: "Chuck Berry", y: 1955},
{t: "Merry Go Round", a: "Kacey Musgraves", y: 2013},
{t: "Midnight Train to Georgia", a: "Gladys Knight and the Pips", y: 1973},
{t: "Mind Playing Tricks on Me", a: "Geto Boys", y: 1991},
{t: "Mississippi Goddam", a: "Nina Simone", y: 1964},
{t: "More Than a Feeling", a: "Boston", y: 1976},
{t: "Move On Up", a: "Curtis Mayfield", y: 1970},
{t: "Move Your Body (The House Music Anthem)", a: "Marshall Jefferson", y: 1986},
{t: "Mr. Brightside", a: "The Killers", y: 2004},
{t: "Mr. Brightside", a: "The Killers", y: 2003},
{t: "Mr. Tambourine Man", a: "Bob Dylan", y: 1965},
{t: "Mr. Tambourine Man", a: "The Byrds", y: 1965},
{t: "Ms. Jackson", a: "Outkast", y: 2000},
{t: "My Generation", a: "The Who", y: 1965},
{t: "My Girl", a: "The Temptations", y: 1965},
{t: "Never Tear Us Apart", a: "INXS", y: 1988},
{t: "Never Too Much", a: "Luther Vandross", y: 1981},
{t: "Night Moves", a: "Bob Seger", y: 1976},
{t: "Nightswimming", a: "R.E.M.", y: 1992},
{t: "No Diggity", a: "Blackstreet feat. Dr. Dre and Queen Pen", y: 1996},
{t: "No Ordinary Love", a: "Sade", y: 1992},
{t: "No Scrubs", a: "TLC", y: 1999},
{t: "No Woman No Cry", a: "Bob Marley and the Wailers", y: 1975},
{t: "Nothing Compares 2 U", a: "Sinead O Connor", y: 1990},
{t: "Nothing Compares 2 U", a: "Sinéad O’Connor", y: 1990},
{t: "Nuthin but a G Thang", a: "Dr. Dre feat. Snoop Doggy Dogg", y: 1992},
{t: "Ode to Billie Joe", a: "Bobbie Gentry", y: 1967},
{t: "Oh Bondage! Up Yours!", a: "X-Ray Spex", y: 1977},
{t: "Old Town Road", a: "Lil Nas X", y: 2019},
{t: "Once in a Lifetime", a: "Talking Heads", y: 1980},
{t: "One", a: "U2", y: 1992},
{t: "One Nation Under a Groove", a: "Funkadelic", y: 1978},
{t: "Ooh La La", a: "Faces", y: 1973},
{t: "Our Lips Are Sealed", a: "The Go-Gos", y: 1981},
{t: "Oye Como Va", a: "Santana", y: 1970},
{t: "Paid in Full", a: "Eric B. and Rakim", y: 1987},
{t: "Paint It", a: "The Rolling Stones", y: 1966},
{t: "Paint It Black", a: "Rolling Stones", y: 1966},
{t: "Pancho and Lefty", a: "Townes Van Zandt", y: 1972},
{t: "Papa Was a Rollin Stone", a: "The Temptations", y: 1972},
{t: "Papas Got a Brand New Bag", a: "James Brown", y: 1966},
{t: "Paper Bag", a: "Fiona Apple", y: 1999},
{t: "Paper Planes", a: "M.I.A.", y: 2008},
{t: "Paranoid", a: "Black Sabbath", y: 1970},
{t: "Party Up (Up in Here)", a: "DMX", y: 1999},
{t: "Passionate Kisses", a: "Lucinda Williams", y: 1988},
{t: "Peggy Sue", a: "Buddy Holly", y: 1958},
{t: "People Get Ready", a: "The Impressions", y: 1965},
{t: "Personality Crisis", a: "New York Dolls", y: 1973},
{t: "Pink Moon", a: "Nick Drake", y: 1972},
{t: "Planet Rock", a: "Afrika Bambaataa and the Soulsonic Force", y: 1982},
{t: "Please Mr. Postman", a: "The Marvelettes", y: 1961},
{t: "Poker Face", a: "Lady Gaga", y: 2008},
{t: "Ponta de Lança Africano (Umbabarauma)", a: "Jorge Ben", y: 1976},
{t: "Portions for Foxes", a: "Rilo Kiley", y: 2004},
{t: "Powderfinger", a: "Neil Young", y: 1979},
{t: "Pressure Drop", a: "Toots and the Maytals", y: 1973},
{t: "Promised Land", a: "Chuck Berry", y: 1964},
{t: "Proud Mary", a: "Creedence Clearwater Revival", y: 1969},
{t: "Pt. 1-Acknowledgement", a: "John Coltrane", y: 1965},
{t: "Purple Haze", a: "The Jimi Hendrix Experience", y: 1967},
{t: "Purple Rain", a: "Prince", y: 1984},
{t: "Purple Rain", a: "Prince and the Revolution", y: 1984},
{t: "Pusherman", a: "Curtis Mayfield", y: 1972},
{t: "Radiation Vibe", a: "Fountains of Wayne", y: 1996},
{t: "Radio Free Europe", a: "R.E.M.", y: 1983},
{t: "Rappers Delight", a: "Sugar Hill Gang", y: 1979},
{t: "Reach Out (Ill Be There)", a: "The Four Tops", y: 1967},
{t: "Real Love", a: "Mary J. Blige", y: 1992},
{t: "Rebel Girl", a: "Bikini Kill", y: 1993},
{t: "Redbone", a: "Childish Gambino", y: 2016},
{t: "Redemption Song", a: "Bob Marley and the Wailers", y: 1980},
{t: "Rehab", a: "Amy Winehouse", y: 2006},
{t: "Respect", a: "Aretha Franklin", y: 1967},
{t: "Respect", a: "Aretha Franklin", y: 1967},
{t: "Rhythm Nation", a: "Janet Jackson", y: 1989},
{t: "Rid of Me", a: "PJ Harvey", y: 1993},
{t: "Ring of Fire", a: "Johnny Cash", y: 1963},
{t: "Ripple", a: "The Grateful Dead", y: 1970},
{t: "River", a: "Joni Mitchell", y: 1971},
{t: "River Deep", a: "Ike and Tina Turner", y: 1966},
{t: "Roadrunner", a: "The Modern Lovers", y: 1976},
{t: "Rock Lobster", a: "The B-52’s", y: 1978},
{t: "Rock With You", a: "Michael Jackson", y: 1979},
{t: "Rock and Roll All Nite", a: "Kiss", y: 1975},
{t: "Rocket Man", a: "Elton John", y: 1972},
{t: "Rolling in the Deep", a: "Adele", y: 2010},
{t: "Rolling in the Deep", a: "Adele", y: 2011},
{t: "Rosalita (Come Out Tonight)", a: "Bruce Springsteen", y: 1973},
{t: "Royals", a: "Lorde", y: 2011},
{t: "Runaway", a: "Kanye West feat. Pusha T", y: 2010},
{t: "Running Up That Hill", a: "Kate Bush", y: 1985},
{t: "Sabotage", a: "Beastie Boys", y: 1994},
{t: "Safaera", a: "Bad Bunny", y: 2020},
{t: "Sail Away", a: "Randy Newman", y: 1972},
{t: "Savage (Remix)", a: "Megan Thee Stallion feat. Beyoncé", y: 2020},
{t: "Say It Loud (Im Black and Im Proud)", a: "James Brown", y: 1968},
{t: "Say My Name", a: "Destiny’s Child", y: 1999},
{t: "Scenes From an Italian Restaurant", a: "Billy Joel", y: 1977},
{t: "Schools Out", a: "Alice Cooper", y: 1972},
{t: "September Gurls", a: "Big Star", y: 1974},
{t: "Seven Nation Army", a: "White Stripes", y: 2003},
{t: "Seven Nation Army", a: "The White Stripes", y: 2003},
{t: "Sexual Healing", a: "Marvin Gaye", y: 1982},
{t: "Shape of You", a: "Ed Sheeran", y: 2017},
{t: "She Loves You", a: "The Beatles", y: 1964},
{t: "Sheena Is a Punk Rocker", a: "Ramones", y: 1977},
{t: "Shes Gone", a: "Hall and Oates", y: 1973},
{t: "Shook Ones", a: "Mobb Deep", y: 1995},
{t: "Shout (Parts 1 and 2)", a: "The Isley Brothers", y: 1959},
{t: "Signed", a: "Stevie Wonder", y: 1970},
{t: "Since U Been Gone", a: "Kelly Clarkson", y: 2004},
{t: "Single Ladies (Put a Ring On It)", a: "Beyoncé", y: 2008},
{t: "Smells Like Teen Spirit", a: "Nirvana", y: 1991},
{t: "Smells Like Teen Spirit", a: "Nirvana", y: 1991},
{t: "So What", a: "Miles Davis", y: 1959},
{t: "Solsbury Hill", a: "Peter Gabriel", y: 1977},
{t: "Somebody That I Used To Know", a: "Gotye", y: 2011},
{t: "Something", a: "The Beatles", y: 1969},
{t: "Son of a Preacher Man", a: "Dusty Springfield", y: 1968},
{t: "Space Oddity", a: "David Bowie", y: 1969},
{t: "Spoonful", a: "Howlin’ Wolf", y: 1960},
{t: "Spring Day", a: "BTS", y: 2017},
{t: "Springsteen", a: "Eric Church", y: 2011},
{t: "Stairway to Heaven", a: "Led Zeppelin", y: 1971},
{t: "Stairway to Heaven", a: "Led Zeppelin", y: 1971},
{t: "Stan", a: "Eminem feat. Dido", y: 2000},
{t: "Stand by Me", a: "Ben E. King", y: 1961},
{t: "Stand by Your Man", a: "Tammy Wynette", y: 1968},
{t: "Stayin Alive", a: "Bee Gees", y: 1977},
{t: "Stayin' Alive", a: "Bee Gees", y: 1977},
{t: "Stills", a: "Crosby", y: 1969},
{t: "Stop! In the Name of Love", a: "The Supremes", y: 1965},
{t: "Straight Outta Compton", a: "N.W.A", y: 1988},
{t: "Strange Fruit", a: "Billie Holiday", y: 1939},
{t: "Strawberry Fields Forever", a: "The Beatles", y: 1967},
{t: "Stronger", a: "Kanye West", y: 2007},
{t: "Subterranean Homesick Blues", a: "Bob Dylan", y: 1965},
{t: "Sucker MCs", a: "Run-DMC", y: 1984},
{t: "Sugar", a: "Fall Out Boy", y: 2005},
{t: "Summer Babe (Winter Version)", a: "Pavement", y: 1992},
{t: "Summertime Blues", a: "Eddie Cochran", y: 1958},
{t: "Sunday Mornin Comin Down", a: "Kris Kristofferson", y: 1970},
{t: "Super Bass", a: "Nicki Minaj", y: 2010},
{t: "Super Freak", a: "Rick James", y: 1981},
{t: "Superstition", a: "Stevie Wonder", y: 1972},
{t: "Surrender", a: "Cheap Trick", y: 1978},
{t: "Suspicious Minds", a: "Elvis Presley", y: 1969},
{t: "Suzanne", a: "Leonard Cohen", y: 1967},
{t: "Sweet Child O Mine", a: "Guns N Roses", y: 1987},
{t: "Sweet Child O Mine", a: "Guns N’ Roses", y: 1987},
{t: "Sweet Dreams (Are Made of This)", a: "Eurythmics", y: 1983},
{t: "Sweet Jane", a: "The Velvet Underground", y: 1970},
{t: "Sympathy for the Devil", a: "The Rolling Stones", y: 1968},
{t: "Tangled Up in Blue", a: "Bob Dylan", y: 1975},
{t: "Teenage Riot", a: "Sonic Youth", y: 1988},
{t: "Thank U", a: "Ariana Grande", y: 2019},
{t: "Thatll Be the Day", a: "Buddy Holly", y: 1957},
{t: "Thats the Joint", a: "The Funky 4 + 1", y: 1980},
{t: "The Boys Are Back in Town", a: "Thin Lizzy", y: 1976},
{t: "The Harder They Come", a: "Jimmy Cliff", y: 1972},
{t: "The House That Built Me", a: "Miranda Lambert", y: 2010},
{t: "The House of the Rising Sun", a: "The Animals", y: 1964},
{t: "The Humpty Dance", a: "Digital Underground", y: 1990},
{t: "The Message", a: "Grandmaster Flash and the Furious Five", y: 1982},
{t: "The Rain (Supa Dupa Fly)", a: "Missy Elliot", y: 1997},
{t: "The Revolution Will Not Be Televised", a: "Gil-Scott Heron", y: 1971},
{t: "The Sounds of Silence", a: "Simon and Garfunkel", y: 1964},
{t: "The Tears of a Clown", a: "Smokey Robinson and the Miracles", y: 1967},
{t: "The Tracks of My Tears", a: "Smokey Robinson and the Miracles", y: 1965},
{t: "The Weight", a: "The Band", y: 1968},
{t: "There Is a Light That Never Goes Out", a: "The Smiths", y: 1986},
{t: "They Reminisce Over You", a: "Pete Rock and CL Smooth", y: 1992},
{t: "Thinkin Bout You", a: "Frank Ocean", y: 2012},
{t: "This Land Is Your Land", a: "Woody Guthrie", y: 1951},
{t: "This Must Be the Place (Naive Melody)", a: "Talking Heads", y: 1983},
{t: "Thunder Road", a: "Bruce Springsteen", y: 1975},
{t: "Time After Time", a: "Cyndi Lauper", y: 1983},
{t: "Time of the Season", a: "The Zombies", y: 1968},
{t: "Tiny Dancer", a: "Elton John", y: 1972},
{t: "Titi Me Pregunto", a: "Bad Bunny", y: 2022},
{t: "Toxic", a: "Britney Spears", y: 2003},
{t: "Trans-Europe Express", a: "Kraftwerk", y: 1977},
{t: "Truth Hurts", a: "Lizzo", y: 2017},
{t: "Try a Little Tenderness", a: "Otis Redding", y: 1966},
{t: "Tumbling Dice", a: "The Rolling Stones", y: 1972},
{t: "Tutti-Frutti", a: "Little Richard", y: 1955},
{t: "Typical Girls", a: "The Slits", y: 1979},
{t: "Tyrone", a: "Erykah Badu", y: 1997},
{t: "Umbrella", a: "Rihanna", y: 2007},
{t: "Unchained Melody", a: "The Righteous Brothers", y: 1965},
{t: "Under Pressure", a: "Queen and David Bowie", y: 1981},
{t: "Under the Bridge", a: "Red Hot Chili Peppers", y: 1991},
{t: "Untitled (How Does It Feel)", a: "D’Angelo", y: 2000},
{t: "Up on the Roof", a: "The Drifters", y: 1964},
{t: "Uptown Funk", a: "Mark Ronson feat. Bruno Mars", y: 2015},
{t: "Virginia Plain", a: "Roxy Music", y: 1972},
{t: "Visions of Johanna", a: "Bob Dylan", y: 1966},
{t: "Vogue", a: "Madonna", y: 1990},
{t: "Walk on By", a: "Dionne Warwick", y: 1964},
{t: "Walk on By", a: "Isaac Hayes", y: 1969},
{t: "Walk on the Wild Side", a: "Lou Reed", y: 1972},
{t: "Wannabe", a: "Spice Girls", y: 1996},
{t: "Waterfalls", a: "TLC", y: 1995},
{t: "Waterloo Sunset", a: "The Kinks", y: 1967},
{t: "West End Girls", a: "Pet Shop Boys", y: 1984},
{t: "What a Fool Believes", a: "The Doobie Brothers", y: 1979},
{t: "What a Wonderful World", a: "Louis Armstrong", y: 1967},
{t: "Whatd I Say", a: "Ray Charles", y: 1957},
{t: "Whats Going On", a: "Marvin Gaye", y: 1971},
{t: "Whats Love Got to Do With It", a: "Tina Turner", y: 1984},
{t: "When Doves Cry", a: "Prince and the Revolution", y: 1984},
{t: "Where Is My Mind?", a: "The Pixies", y: 1988},
{t: "Whipping Post", a: "Allman Brothers Band", y: 1969},
{t: "White Rabbit", a: "Jefferson Airplane", y: 1967},
{t: "Whole Lotta Love", a: "Led Zeppelin", y: 1969},
{t: "Wichita Lineman", a: "Glen Campbell", y: 1968},
{t: "Wild Horses", a: "The Rolling Stones", y: 1971},
{t: "Will You Love Me Tomorrow", a: "The Shirelles", y: 1960},
{t: "Wind", a: "Earth", y: 1978},
{t: "Wish You Were Here", a: "Pink Floyd", y: 1975},
{t: "With or Without You", a: "U2", y: 1987},
{t: "Without You", a: "Harry Nilsson", y: 1971},
{t: "Wonderwall", a: "Oasis", y: 1995},
{t: "Wont Get Fooled Again", a: "The Who", y: 1971},
{t: "Work It", a: "Missy Elliott", y: 2000},
{t: "Wouldnt It Be Nice", a: "Beach Boys", y: 1966},
{t: "Yeah!", a: "Usher feat. Lil Jon and Ludacris", y: 2004},
{t: "Yesterday", a: "The Beatles", y: 1965},
{t: "You Are the Sunshine of My Life", a: "Stevie Wonder", y: 1972},
{t: "You Keep Me Hangin On", a: "The Supremes", y: 1966},
{t: "You Make Me Feel (Mighty Real)", a: "Sylvester", y: 1978},
{t: "You Oughta Know", a: "Alanis Morissette", y: 1995},
{t: "You Really Got Me", a: "The Kinks", y: 1964},
{t: "You Shook Me All Night Long", a: "AC/DC", y: 1980},
{t: "Young Americans", a: "David Bowie", y: 1975},
{t: "Your Cheatin Heart", a: "Hank Williams", y: 1953},
{t: "Your Song", a: "Elton John", y: 1970},
{t: "Youre So Vain", a: "Carly Simon", y: 1972},
{t: "…Baby One More Time", a: "Britney Spears", y: 1998},
];
